### PR TITLE
Syntax highlight code blocks in docs

### PR DESCRIPTION
**Pull request by ianprime0509**
Any code block which does not have an explicit tag or is tagged as `zig` is highlighted as Zig code. This also includes a small tweak to source code rendering to properly highlight (non-doc) comments as such.

---

Points of interest:

- `#std.log`
- `#std.Thread.Condition`
- `#std.testing.checkAllAllocationFailures` (contains several occurrences)

### CODE REVIEW

**Comment by andrewrk** [comment]
Hmmmmm perhaps should the zig code be fully parsed and linkified, as if it were a snippet of code within the context of whatever namespace the code snippet appears in? That's how we would want guides to work, right?

**Comment by andrewrk** [comment]
I'm not sure if this is a good idea or not, but one thing to try would be to parse doc comments up front during the main walk(), then the code snippets would be evaluated within the scope they appear in.

**Comment by ianprime0509** [comment]
That would be an interesting idea to pursue. The first thing that comes to mind as a potential issue for doing that for all code blocks in doc comments is that the Zig code represented is less likely to be consistently parseable than, say, a doctest, since there's no enforced structure.

Here's a list of all the code blocks in the standard library today which are either untagged or tagged as Zig, categorized by what they contain:

- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/Thread/Semaphore.zig#L7-L19 (mixture of container-scope and block-scope content)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/Thread/Mutex.zig#L7-L20 (block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/Thread/Condition.zig#L6-L32 (mixture of container-scope and block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/Thread/Condition.zig#L36-L43 (explanatory content, not valid Zig code)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/Build/Cache.zig#L388-L390 (either container-scope or block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/log.zig#L18-L68 (block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/log.zig#L70-L73 (log output, not Zig code)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/fmt.zig#L70-L72 (incomplete, partially invalid Zig code)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/testing.zig#L990-L1000 (block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/testing.zig#L1005-L1019 (block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/testing.zig#L1024-L1031 (block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/unicode.zig#L356-L361 (block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/unicode.zig#L1611-L1617 (block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/crypto/kyber_d00.zig#L28-L32 (ASCII diagram, not Zig code)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/math.zig#L432-L440 (ASCII diagram)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/math.zig#L516-L524 (ASCII diagram)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/crypto/hkdf.zig#L29-L35 (block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/json/stringify.zig#L152-L161 (grammar description, not Zig code)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/json/scanner.zig#L74-L88 (ditto)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/json/scanner.zig#L92-L114 (ditto)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/json/scanner.zig#L432-L436 (block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/os/linux/seccomp.zig#L56-L64 (container-scope or block-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/heap/general_purpose_allocator.zig#L53-L67 (table, not Zig code)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/bounded_array.zig#L12-L17 (block-scope, although technically should be parseable at container-scope)
- https://github.com/ziglang/zig/blob/9cf28d1e9bc940b13cd47efb778fd42a4b3b88de/lib/std/bounded_array.zig#L28-L34 (ditto)

Arguably, of these examples, the ones which aren't Zig code at all should be tagged as something else or represented using a different structure (such as a table). But of the ones which are, it's potentially context-dependent as to how they're meant to be read, which could complicate processing them. (And although the current standard library doc comments don't form a standard as-is, I think both types of code blocks are reasonable)

With that said, even if parsing the code in full isn't attempted, we could still try to linkify identifiers and dotted paths of identifiers, but doing that without parsing would be much less accurate.

As far as guides go, the same general comments apply, but I think there's also a third category of Zig code that would be useful to explore for guides, which is full, runnable/testable Zig files or even projects included in the docs, as currently implemented on the ziglang.org website via [zig-doctest](https://github.com/kristoff-it/zig-doctest). I could see this being done either inline with a special code block (e.g. ` ```zig test ` to indicate that the code should be executed as a test case), or by including the content of external files via some directive (what ziglang.org's build does), or both. Such content would be unambiguous in how it's intended to be parsed.

Anyway, without taking this long comment even further off topic, those are my general thoughts on the state and potential of Zig code blocks in doc comments. I'll definitely think about it more; there may be a natural way to distinguish how a code block is meant to be interpreted, or at least a clear direction that could be given to documentation writers to make sure their code blocks are handled optimally by Autodoc (e.g. "write your code blocks as normal block-scope Zig code, or you're only going to get basic syntax highlighting").

**Comment by andrewrk** [comment]
Reading this writeup has convinced me that zig code does not belong in doc comments. We have doctests, tests, and potentially new kinds of ways to actually run the zig code and have it be part of the compilation rather than part of a comment.

In order to encourage this, I think it is better to not syntax highlight code blocks in doc comments.

**Comment by ianprime0509** [comment]
That sounds reasonable to me. The nice things about Zig doctests for me are that 1. they are actually tested and 2. they integrate well with editor tooling, syntax highlighting, `zig fmt`, etc., so it makes sense to ensure new forms of "example" content also share those benefits.

**Pull request closed without merging**
